REST_BASE_URL=http://localhost:8080/Centralni_Registar/api/evidencije/
REST_POTJERNICE=potjernice
REST_DOKUMENTI=dokumenti
ZASTICENA_LOZINKA_ADMIN=RPUekNs5WcMmaDBkcjNTCKLsMGZngvXsmQU12u/ceGs=
SALT_ADMIN=W6ro0Z1t2OX1NUA3YnRK3O4wqFn4Em
RESURSI_DIREKTORIJUM=resources
LOG_DIREKTORIJUM=log
LOG_DATOTEKA=aamdp.log
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_KLJUC_SEPARATOR=:
REDIS_KLJUC_KREDENCIJAL=kredencijal
GRESKA_NIJE_PRONADJEN=GRESKA: ne postoji korisnik u bazi
GRESKA_AKTIVAN=GRESKA: korisnik je vec aktivan
GRESKA_POGRESAN_PROLAZ=GRESKA: odabran je pogresan prolaz
GRESKA_POGRESNA_KONTROLA=GRESKA: odabrana je pogresna kontrola
GRESKA_POGRESNI_KREDENCIJALI=GRESKA: uneseni su pogresni kredencijali
OK=OK
SEPARATOR=#