REST_BASE_URL=http://localhost:8080/Administratorska_Aplikacija/api/korisnici/
POCETNI_DIREKTORIJUM=src
RESURSI_DIREKTORIJUM=resources
LOG_DIREKTORIJUM=log
LOG_DATOTEKA=kamdp.log
DOKUMENTI_DIREKTORIJUM=documents
DOKUMENTI_DIREKTORIJUM_ZIP=documents_zip
KEYSTORE_DIREKTORIJUM=keystore
TRUSTSTORE_PATH=keystore.jks
TRUSTSTORE_PASSWORD=test123
SERVER_PORT=8443
SERVER_ADRESA=localhost
MAX_VELICINA=1000
MULTICAST_ADRESA=228.5.6.7
MULTICAST_PORT=10000
MULTICAST_END=MULTICAST_END
LOGIN=LOGIN
END=END
OK=OK
CHAT_LIST_ADD=CHAT_LIST_ADD
CHAT_LIST_REMOVE=CHAT_LIST_REMOVE
CHAT_MESSAGE=CHAT_MESSAGE
BROADCAST_MESSAGE=BROADCAST_MESSAGE
SEPARATOR=#
SEPARATOR_MC=^NL$
SEPARATOR_KORISNIK=--
OBAVJESTENJE_ADRESA=228.5.6.8
OBAVJESTENJE_PORT=10000
OBAVJESTENJE_OTVOREN=OTVOREN
OBAVJESTENJE_ZATVOREN=ZATVOREN
OBAVJESTENJE_INFO=INFO
OBAVJESTENJE_END=END
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_KLJUC_SEPARATOR=:
REDIS_KLJUC_KREDENCIJAL=kredencijal
POLICY_DIREKTORIJUM=policy
POLICY_DATOTEKA=client_policyfile.txt
RMI_PORT_POTJERNICA=1099
RMI_NAME_POTJERNICA=potjernice