POCETNI_DIREKTORIJUM=src
RESURSI_DIREKTORIJUM=resources
LOG_DIREKTORIJUM=log
LOG_DATOTEKA=csmdp.log
KEYSTORE_DIREKTORIJUM=keystore
KEYSTORE_PATH=keystore.jks
KEYSTORE_PASSWORD=test123
SERVER_PORT=8443
SEPARATOR=#
SEPARATOR_KORISNIK=--
END=END
LOGIN=LOGIN
OK=OK
CHAT_LIST_ADD=CHAT_LIST_ADD
CHAT_LIST_REMOVE=CHAT_LIST_REMOVE
CHAT_MESSAGE=CHAT_MESSAGE
BROADCAST_MESSAGE=BROADCAST_MESSAGE
INVALID_LOGIN=GRESKA#pogresni_kredencijali
INVALID_REQUEST=GRESKA#neispravan_zahtjev