SEPARATOR=#
RESURSI_DIREKTORIJUM=resources
TERMINALI_DIREKTORIJUM=terminals
LOG_DIREKTORIJUM=log
LOG_DATOTEKA=crmdp.log
PROLASCI_DIREKTORIJUM=passings
PROLASCI_TIP_DATOTEKE=.txt
POTJERNICE_DIREKTORIJUM=warrants
DOKUMENTI_DIREKTORIJUM=documents
SERIJALIZACIJA_TIP_DATOTEKE=.out
SERIJALIZACIJA_SEPARATOR=__tip_
TERMINALI_PUTANJA=E:\\Education\\Programiranje\\MDP\\Projektni\\Aktivno\\Centralni_Registar\\src\\resources\\terminals
RESURSI_PUTANJA=E:\\Education\\Programiranje\\MDP\\Projektni\\Aktivno\\Centralni_Registar\\src\\resources