POCETNI_DIREKTORIJUM=src
RESURSI_DIREKTORIJUM=resources
LOG_DIREKTORIJUM=log
LOG_DATOTEKA=psmdp.log
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_KLJUC_SEPARATOR=:
REDIS_KLJUC_KREDENCIJAL=kredencijal